- name: lets play with freshly created chroot
  hosts: chroot
  conncection: chroot

  vars:
    - distrib: trusty
    - components: main restricted universe multiverse
    - add_repo:
      - "http://pl.archive.ubuntu.com/ubuntu {{ distrib }}"
      - "http://pl.archive.ubuntu.com/ubuntu {{ distrib }}-updates"
      - "http://pl.archive.ubuntu.com/ubuntu {{ distrib }}-backports"
      - "http://security.ubuntu.com {{ distrib }}-security"
    - packages:
      - ubuntu-minimal
      - ubuntu-standard
      - python-apt

  tasks:
    - name: remove apt generic source
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse"
        state: absent
        update_cache: no

    - name: add apt sources
      apt_repository:
        repo: "{{ item }} {{ components }}"
        state: present
        update_cache: yes
      with_item: add_repo

    - name: install packages
      apt: pkg='{{ item }}' state=present update_cache=no
      with_items: {{ packages }}

    - name: install default locale
      command: locale-gen en_US.UTF-8

# vim:ft=ansible
